### PR TITLE
Add GHC 9.6 support

### LINKED ISSUE #84: template-haskell bound excludes GHC-9.6
It seems to work fine with allow-newer, so this could be fixed with a revision.

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #84

### CODE REVIEW

**Comment by felixminom** [comment]
Thanks @ysangkok for the PR. I'll take some time between this and next week to give it try.

**Comment by ysangkok** [comment]
@felixminom Much appreciated! Should I submit similar PRs for req and modern-uri?

**Comment by mrkkrp** [comment]
That's something I will do anyway, but right now the upgrade is blocked on `weigh`.

**Comment by ysangkok** [comment]
@mrkkrp Hmm, how is it blocked on `weigh`? I don't see it in the `cabal-plan topo` listing. Sorry for being dense.

**Comment by ysangkok** [comment]
Ooh, I see it now in the benchmark for modern-uri: https://github.com/mrkkrp/modern-uri/blob/b6161a81dbc04af5fa9ae96bd0d6bb23a96ddfdd/modern-uri.cabal#L127

**Comment by felixminom** [comment]
Thanks for the follow-up. I'll keep an eye on this and merge once `weigh`'s PR is ready.

**Comment by ysangkok** [comment]
@felixminom weigh-0.0.17 was released with the necessary changes

**Comment by felixminom** [comment]
@ysangkok thank you, just merged another PR. Will merge this as well and prepare a release.

**Review by felixminom — APPROVED** [review]
Looking good and CI is green. Thanks for your contribution @ysangkok

**Pull request merged**
