### PR TITLE
Test with GHC 9.8.1

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Review by felixminom — APPROVED** [review]
Thanks, looking good. Probably we could have a follow up PR to unify dependencies since most of them (if not all) are redundant, having them centralized will make upcoming PRs like this, easier. wdyt?

**Comment by mrkkrp** [comment]
What do you mean by "redundant"?

**Comment by DavidMazarro** [comment]
@mrkkrp Thanks for the contribution! Remember to add the following line in the PR's description so that the contribution can be considered valid for Stack Builders' Hacktoberfest 2023 event:

> As part of [Stack Builders Inc.](https://www.stackbuilders.com/) Hacktoberfest 2023 event.

**Comment by felixminom** [comment]
@mrkkrp sorry probably I used the wrong terminology, but we are using the same version of the same package for different builds, we could use [common stanzas](https://vrom911.github.io/blog/common-stanzas) so when an update like this happens in the future we just update it in one place.

**Pull request merged**
