### PR TITLE
Test with GHC 9.2.4 and 9.4.1 + misc updates

### PR DESCRIPTION
**Pull request by mrkkrp**

### CODE REVIEW

**Review by sestrella — APPROVED** [review]
@mrkkrp thank you for this contribution 🚀

**Comment by ysangkok** [comment]
@sestrella Would it be possible to release this, or to adjust the bounds with a revision?

**Comment by sestrella** [comment]
@ysangkok thank you for bringing this up, I'm CC'ing this to one of our OSS contributors. @felixminom I noticed you did some contributions lately, would you mind preparing a release with these changes?

**Comment by mrkkrp** [comment]
@ysangkok I've just released a new revision on Hackage.

**Comment by mrkkrp** [comment]
@sestrella @ysangkok Would it be possible to avoid releasing new versions just to bump package bounds? This is, of course, a matter of taste, but I think a revision is the perfect remedy in this kind of situation; otherwise there would be proliferation of package uploads that all contain the same code.

**Pull request merged**
